[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
monitor_echo = yes
monitor_eol = LF

lib_deps = fastled/FastLED@^3.10.3


[env:esp32dev_ota]
platform = espressif32
board = esp32dev
framework = arduino

upload_protocol = espota
upload_port = 192.168.4.1

monitor_speed = 115200
monitor_echo = yes
monitor_eol = LF

lib_deps = fastled/FastLED@^3.10.3